/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfnutricionista.Vistas;

import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import pfnutricionista.AccesoADatos.ComidaData;
import pfnutricionista.AccesoADatos.DietaData;
import pfnutricionista.AccesoADatos.PacienteData;
import pfnutricionista.entidades.Horario;
import pfnutricionista.entidades.Paciente;
import pfnutricionista.entidades.Dieta;

/**
 *
 * @author ivanm
 */
public class abmDietas extends javax.swing.JInternalFrame {

    /**
     * Creates new form abmPacientes
     */
    public abmDietas() {
        initComponents();
        
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jbAlta = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtPacApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdchFechaInicial = new com.toedter.calendar.JDateChooser();
        jdchFechaFinal = new com.toedter.calendar.JDateChooser();
        jftPesoInicial = new javax.swing.JFormattedTextField();
        jftPesoFinal = new javax.swing.JFormattedTextField();
        Apellido = new javax.swing.JLabel();
        jtPacNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ficha de Dietas");
        setToolTipText("");
        setDoubleBuffered(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Nombre de la dieta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Peso Inicial");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("Paciente");

        jtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreKeyTyped(evt);
            }
        });

        jbAlta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbAlta.setText("Alta");
        jbAlta.setToolTipText("");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.setActionCommand("jbModificar");
        jbModificar.setAutoscrolls(true);
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbBaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PLAN DE DIETA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Fecha de Inicio");

        jtPacApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtPacApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPacApellidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Fecha de Fin");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("Peso Final");

        jdchFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jdchFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jftPesoInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jftPesoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftPesoInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jftPesoInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jftPesoFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jftPesoFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftPesoFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Apellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(51, 153, 0));
        Apellido.setText("Apellido");

        jtPacNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtPacNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPacNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(Apellido))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtPacApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtPacNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jdchFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdchFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(14, 14, 14)
                                        .addComponent(jftPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jftPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPacApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPacNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jdchFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jftPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdchFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        Dieta dieta = new Dieta();
        DietaData dietaData = new DietaData();
        if (jtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error. El campo Nombre no puede estar vacio.");
            jtNombre.requestFocus();
        } else {
                    dieta.setNombre(jtNombre.getText());
                    //dieta.setPacinte(jtaDetalle.getText());
                    dieta.setFechaInicial(LocalDate.parse(jdchFechaInicial.getDateFormatString()));
                    dieta.setFechaFinal(LocalDate.parse(jdchFechaFinal.getDateFormatString()));
                    dieta.setPesoInicial(Double.valueOf(jftPesoInicial.getText()));
                    dieta.setPesoFinal(Double.valueOf(jftPesoFinal.getText()));
                    dietaData.modificarDieta(dieta);
                    jtNombre.setText(null); jtPacApellido.setText(null); jdchFechaInicial.setCalendar(null); 
                    jdchFechaFinal.setCalendar(null); jftPesoInicial.setText(null); jftPesoFinal.setText(null);
                    jtNombre.requestFocus();
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Dieta dieta = new Dieta();
        Paciente paciente = new Paciente();
        DietaData dietaData = new DietaData();
        PacienteData pacienteData = new PacienteData();
        if (jtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error. Ingrese el nombre de una dieta.");
            jtNombre.requestFocus();
        } else {
            dieta = dietaData.buscarDieta(jtNombre.getText());
            paciente = pacienteData.buscarPaciente(dieta.getPaciente().getIdPaciente());
            if (dieta==null){
                jtNombre.setText(null); jtPacApellido.setText(null); jdchFechaInicial.setCalendar(null); 
                jdchFechaFinal.setCalendar(null); jftPesoInicial.setText(null); jftPesoFinal.setText(null);
                jtNombre.requestFocus();
            } else {
                jtNombre.setText(dieta.getNombre());
                jtPacApellido .setText(paciente.getApellido()+", "+paciente.getNombre());
                jdchFechaInicial.setDate((Date.valueOf(dieta.getFechaInicial())));
                jdchFechaFinal.setDate(Date.valueOf(dieta.getFechaFinal()));
                jftPesoInicial.setText(Double.toString(dieta.getPesoInicial()));
                jftPesoFinal.setText(Double.toString(dieta.getPesoFinal()));
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        Dieta dieta = new Dieta();
        DietaData dietaData = new DietaData();
        Paciente paciente = new Paciente();
        PacienteData pacienteData = new PacienteData();
        if (jtNombre.getText().equals("") && jtPacApellido.getText().equals("") && jdchFechaInicial.getCalendar().equals("") && jftPesoInicial.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error. Los campos no pueden estar vacio.");
            jtNombre.requestFocus();
        }
       
        paciente = pacienteData.buscarPaciente(jtPacApellido.getText(), jtPacNombre.getText());
        dieta.setNombre(jtNombre.getText());
        dieta.setPaciente(paciente);
        dieta.setFechaInicial((jdchFechaInicial.getDate()));
        dieta.setFechaFinal((jdchFechaFinal.getDate()));
        dieta.setPesoInicial(Double.valueOf(jftPesoInicial.getText()));
        dieta.setPesoFinal(Double.valueOf(jftPesoFinal.getText()));
        dietaData.guardarDieta(dieta, paciente);
        jtNombre.setText(null); jtPacApellido.setText(null); jtPacNombre.setText(null);
        jdchFechaInicial.setDateFormatString(""); jdchFechaFinal.setDateFormatString("");
        jftPesoInicial.getText(); jftPesoFinal.getText();
        jtNombre.requestFocus();
        
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        Dieta dieta = new Dieta();
        DietaData dietaData = new DietaData();
        if (jtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error. El campo Nombre no puede estar vacio.");
            jtNombre.requestFocus();
        } else {
            dieta = dietaData.buscarDieta(jtNombre.getText());
            dietaData.eliminarDieta(dieta.getIdDieta());
            jtNombre.setText(null); jtPacApellido.setText(null);  jtPacNombre.setText(null);
            jdchFechaInicial.setDateFormatString(""); jdchFechaFinal.setDateFormatString(""); 
            jftPesoInicial.setText(null); jftPesoFinal.setText(null);
        }
    }//GEN-LAST:event_jbBajaActionPerformed

    
    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyTyped
        jtNombre.setText (jtNombre.getText().toUpperCase());
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtPacApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPacApellidoActionPerformed
        jtPacApellido.setText (jtPacApellido.getText().toUpperCase());
    }//GEN-LAST:event_jtPacApellidoActionPerformed

    private void jtPacNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPacNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPacNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbModificar;
    private com.toedter.calendar.JDateChooser jdchFechaFinal;
    private com.toedter.calendar.JDateChooser jdchFechaInicial;
    private javax.swing.JFormattedTextField jftPesoFinal;
    private javax.swing.JFormattedTextField jftPesoInicial;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPacApellido;
    private javax.swing.JTextField jtPacNombre;
    // End of variables declaration//GEN-END:variables
}
